#!/usr/bin/env bash
# Configures /etc/hosts to redirect localhost and facebook.com
hosts_content=$(sed 's/127.0.0.1/127.0.0.2/g' /etc/hosts)
echo "$hosts_content" | sudo tee /etc/hosts > /dev/null
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
